spdx/tools-golang

v0/builder/builder2v1/build_creation_info.go

Builder package will now use UTC for Creationinfo.Created instead of local time. 
Fixes issue #2

Fix local time issue in CreationInfo.Created

---

docs/tvloader-assumptions.md
v0/tvloader/parser2v1/parse_other_license.go
v0/tvloader/parser2v1/parse_other_license_test.go
v0/tvloader/parser2v1/parse_review.go
v0/tvloader/parser2v1/parse_review_test.go

Fixes #10 
Also fixes the same problem for Review sections, in addition to OtherLicense sections.
Also removes the (then-true, now-incorrect) section of tvloader-assumptions.md which says that OtherLicense and Review sections will not parse Relationships / Annotations that appear after them.

Fix tvloader parsing Relationships and Annotations

---

v0/rdfloader/rdf2v1/Annotation.go
v0/rdfloader/rdf2v1/Checksum.go
v0/rdfloader/rdf2v1/CreationInfo.go
v0/rdfloader/rdf2v1/Document.go
v0/rdfloader/rdf2v1/ExtractedLicensingInfo.go
v0/rdfloader/rdf2v1/File.go
v0/rdfloader/rdf2v1/License.go
v0/rdfloader/rdf2v1/Package.go
v0/rdfloader/rdf2v1/ProcessTerm.go
v0/rdfloader/rdf2v1/Relationship.go
v0/rdfloader/rdf2v1/Review.go
v0/rdfloader/rdf2v1/Snippet.go
v0/rdfloader/rdf2v1/reader.go
v0/rdfloader/rdf2v1/transferTo2_1.go
v0/rdfloader/rdfloader.go

Signed-off-by: abhishekspeer.abhishek.abhishekgaur.gaur@gmail.com
Transfer script added to Converter from Intermediate to Main data structure.

Converter from Intermediate to Main data structure

---

v0/rdfloader/rdf2v1/transferToIntermediate.go

Signed-off-by: abhishekspeer.abhishek.abhishekgaur.gaur@gmail.com
Transfer script added to Convert from Main to Intermediate data structure.

Converter from Main to Intermediate data structure 

---

rdfloader/parser2v2/parse_file.go
rdfloader/parser2v2/parse_file_test.go
rdfloader/parser2v2/parse_license.go
rdfloader/parser2v2/parse_license_test.go
rdfloader/parser2v2/parse_package.go
rdfloader/parser2v2/parse_package_test.go
rdfloader/parser2v2/parse_relationship.go
rdfloader/parser2v2/parse_relationship_test.go
rdfloader/parser2v2/parser.go
rdfloader/parser2v2/types.go

- File, Package, Relationship can have cyclic dependent objects.
- Cyclic dependent License will raise an error.
- Double computation for File, Package, Relationship, and License is enabled.
This fixes #55 and attempts to fix #51.
@swinslow, this time, I've personally checked if the parsed document has all the bits from the [canonical sample SPDX RDF file](https://github.com/spdx/spdx-spec/blob/development/v2.2.1/examples/SPDXRdfExample-v2.2.spdx.rdf.xml).
Please let me know if there are still any missing elements in the parsed document.
Also, please feel free to try it out using other documents as well. 
Signed-off-by: Rishabh Bhatnagar <bhatnagarrishabh4@gmail.com>

Enable Caching And Parse Cyclic Dependent Objects

---

README.md

Updating the README reference to the license files' filenames after #65

Fix reference to license filenames

---

.gitignore
tvsaver/saver2v1/save_snippet.go
tvsaver/saver2v1/save_snippet_test.go
tvsaver/saver2v2/save_snippet.go
tvsaver/saver2v2/save_snippet_test.go

Signed-off-by: Bisakh Mondal bisakhmondal00@gmail.com
This is a fix for wrapping multiline snippet copyright in `<text></text>` block in `tvsaver` package. Hope this may close #31.

Fix for wrapping multiline snippet copyright in tvsaver

---

spdx/identifier.go
tvloader/parser2v2/parse_relationship.go
tvloader/parser2v2/parse_relationship_test.go
tvloader/parser2v2/util.go
tvloader/parser2v2/util_test.go
tvsaver/saver2v2/save_relationship_test.go

In SPDX 2.2, the right-hand side of Relationships are not limited
to SPDX IDs; they can also include the special values NONE and
NOASSERTION.
To handle these, since Golang doesn't (to my knowledge) have a
concept of union types, and since I don't want to use interface{},
this commit instead adds a new SpecialID field to DocElementID.
When SpecialID is non-empty, it should be treated as being a
"special" ID value, and DocumentRefID / ElementRefID should be
ignored.
(Unfortunately, we can't just use ElementRefID == "NONE", etc.
for this purpose, because in theory an SPDX document could define
the identifier SPDXRef-NONE to mean something. Even though they
really, really shouldn't do that.)
This commit updates tvloader and tvsaver to appropriately handle
the possibility of NONE and …

Fix special IDs for right-side 2.2 Relationships

---

spdxlib/described_elements.go
spdxlib/described_elements_test.go
spdxlib/documents.go
spdxlib/documents_test.go
spdxlib/element_ids.go
spdxlib/element_ids_test.go
spdxlib/relationships.go
spdxlib/relationships_test.go

Addresses #71 
Adds a function for filtering relationships to retrieve an arbitrary set of ElementIDs. This can be seen in action in described_elements.go:
```
eIDs, err := FilterRelationships2_1(doc, func(relationship *spdx.Relationship2_1) *spdx.ElementID {
refDocument := spdx.MakeDocElementID("", "DOCUMENT")
if relationship.Relationship == "DESCRIBES" && relationship.RefA == refDocument {
return &relationship.RefB.ElementRefID
} else if relationship.Relationship == "DESCRIBED_BY" && relationship.RefB == refDocument {
return &relationship.RefA.ElementRefID
}
return nil
})
```
This retrieves a slice of all the ElementIDs that are described by the document, accounting for both DESCRIBES and DESCRIBED_BY relationship types.
This function was intended to be generic so that additional …

Add relationship filter function

---

tvsaver/saver2v1/save_document_test.go
tvsaver/saver2v1/save_file_test.go
tvsaver/saver2v1/save_snippet.go
tvsaver/saver2v1/save_snippet_test.go
tvsaver/saver2v2/save_document_test.go
tvsaver/saver2v2/save_file_test.go
tvsaver/saver2v2/save_snippet.go
tvsaver/saver2v2/save_snippet_test.go

Fix incorrect tag for Snippet IDs in tvsaver

---

jsonloader/parser2v2/parse_files_test.go
jsonloader/parser2v2/parse_other_license.go
jsonloader/parser2v2/parse_other_license_test.go
jsonsaver/saver2v2/save_document_test.go
jsonsaver/saver2v2/save_files.go
jsonsaver/saver2v2/save_files_test.go
jsonsaver/saver2v2/save_package.go

GSoC'2021 Pull Request 7 :
Deliverables Completed :

[GSoC'21] Pr:7 . JSON saver bug fix

---

docs/jsonloader.md
docs/jsonsaver.md
jsonsaver/jsonsaver.go
jsonsaver/jsonsaver_test.go
jsonsaver/saver2v2/save_document.go
jsonsaver/saver2v2/save_files.go
jsonsaver/saver2v2/save_files_test.go
jsonsaver/saver2v2/save_package.go
jsonsaver/saver2v2/save_package_test.go
jsonsaver/saver2v2/save_snippets.go
jsonsaver/saver2v2/save_snippets_test.go

GSoC'2021 Pull Request 7 :
Deliverables Completed :

[GSoC'21] Pr:8 . JSON saver bug fixes and Documentation enhancements 

---

jsonsaver/saver2v2/save_creation_info.go
jsonsaver/saver2v2/save_files.go
jsonsaver/saver2v2/save_files_test.go
jsonsaver/saver2v2/save_other_license.go
jsonsaver/saver2v2/save_other_license_test.go
jsonsaver/saver2v2/save_package.go
jsonsaver/saver2v2/save_package_test.go
jsonsaver/saver2v2/save_relationships.go
jsonsaver/saver2v2/save_relationships_test.go
jsonsaver/saver2v2/save_reviews.go
jsonsaver/saver2v2/save_reviews_test.go
jsonsaver/saver2v2/save_snippets.go
jsonsaver/saver2v2/save_snippets_test.go

jsonsaver: omit empty lists rather than null

---

README.md

Add badges and documentation links

---

.github/workflows/build.yml

After the branch renaming from 'master' to 'main' in 0.2.0 per #69,
the tests were being run by GitHub Actions on the 'main' branch.
However, the code coverage tooling appears to still have been
pulling the old 'master' branch and therefore was not including
later changes such as the new JSON code. This PR fixes this by
changing the branch name in the GitHub Actions config file.

Fix pulling main branch for code coverage

---

README.md

docs: Add jsonsaver to README

---

builder/build_test.go
builder/builder2v1/build_file.go
builder/builder2v1/build_file_test.go
builder/builder2v1/build_package_test.go
builder/builder2v2/build_file.go
builder/builder2v2/build_file_test.go
builder/builder2v2/build_package_test.go

builder: Add missing LicenseInfoInFile field

---

RELEASE-NOTES.md

Update release notes for 0.3.0-rc1

---

README.md
go.mod
go.sum
yaml/parser.go
yaml/writer.go
yaml/yaml_test.go

Depends on (and contains the commit from) https://github.com/spdx/tools-golang/pull/133. Closes #135 
Adds YAML support.
Note to self: rebase before undrafting

YAML support

---

spdx/common/identifier.go
spdx/common/identifier_test.go

This PR corrects an issue with JSON encoding & decoding of `ElementID` which was not consistently handling `SPDXRef-` prefixes in IDs -- it was only encoding and decoding these for `DocElementID`. In addition to fixing this inconsistency in the JSON, this makes handling consistent with what [the tag-value parser is doing](https://github.com/spdx/tools-golang/blob/main/tvloader/parser2v3/util.go#L108).

fix: JSON encoding and decoding not properly handling SPDXRef- prefixes

---

rdfloader/parser2v2/parse_file.go
rdfloader/parser2v2/parse_file_test.go
rdfloader/parser2v2/parse_package.go
rdfloader/parser2v2/parse_package_test.go
rdfloader/parser2v3/parse_file.go
rdfloader/parser2v3/parse_file_test.go
rdfloader/parser2v3/parse_package.go
rdfloader/parser2v3/parse_package_test.go
spdx/v2_2/package.go
spdx/v2_3/package.go
tvloader/parser2v2/parse_file.go
tvloader/parser2v2/parse_file_test.go
tvloader/parser2v2/parse_package.go
tvloader/parser2v2/parse_package_test.go
tvloader/parser2v3/parse_file.go
tvloader/parser2v3/parse_file_test.go
tvloader/parser2v3/parse_package.go
tvloader/parser2v3/parse_package_test.go

This PR updates the 2.2 and 2.3 parsers to support files and packages checksummed with all valid algorithms. 
This PR updates the packages parsers, file parsers, and all test cases to support all valid [2.2](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#710-package-checksum-field) and [2.3](https://spdx.github.io/spdx-spec/v2.3/package-information/#710-package-checksum-field) hashing algorithms:
| SPDX 2.2 | SPDX 2.3 |
| --- | --- |
| SHA1 | SHA1 |
| SHA224 | SHA224 |
| SHA256 | SHA256 |
| SHA384 | SHA384 |
| SHA512 | SHA512 |
| MD2 | MD2 |
| MD4 | MD4 |
| MD5 | MD5 |
| MD6 | MD6 |
|  | SHA3_256 |
|  | SHA3_384 |
|  | SHA3_512 |
|  | BLAKE2b_256 |
|  | BLAKE2b_384 |
|  | BLAKE2b_512 |
|  | BLAKE3 |
|  | ADLER32 |
/cc @lumjjb 
Signed-off-by: Adolfo García Veytia (Puerco) …

Expand algorithm support to all valid ones

---

spdx/v2_1/creation_info.go
spdx/v2_1/document.go
spdx/v2_1/file.go
spdx/v2_1/package.go
spdx/v2_2/creation_info.go
spdx/v2_2/document.go
spdx/v2_2/package.go
spdx/v2_3/creation_info.go
spdx/v2_3/package.go

Related to #156.
It looks like some of the struct tags between different SPDX versions (v2.1, v2.2 and v2.3) were slightly out-of-sync. This results in some of the deprecated fields, non-spec compliant fields being exported by the `json.Save` family of functions, but inconsistently between versions. Additionally, some optional comment fields were not marked with `omitempty`, resulting in unnecessary JSON output.
This PR fixes these various inconsistencies.

Ensure consistency between JSON struct tags across different SPDX versions

---

README.md

The README file currently states that tools-golang has no dependencies other than spdx/gordf and the Go standard library.
With the addition of the YAML functionality and usage of go-cmp, this is no longer an accurate statement. Rather than calling out the specific dependencies, this commit just removes that section. Users are able to check go.mod and go.sum if they want to know which dependencies are required.

docs: Remove outdated statement about requirements

---

README.md
RELEASE-NOTES.md

Create release notes for v0.4.0
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

release: Update docs for 0.4.0 release

---

json/writer.go

The Save2_3 function documentation in the spdx_json module appears to be out of date.

Fix function documentation

---

convert/spdx_document_conversion_test.go

This PR updates the `spdx_document_conversion_test.go` to use the `convert.Document` function, which exercises the full conversion chain on SPDX document objects instead of just calling the `go-struct-converter Convert` function.

chore: update document conversion test to use conversion chain

---

.github/workflows/dependabot.yml

- Add Dependabot workflows for Go modules and GitHub Actions
- Ensure dependencies are up-to-date with the latest security patches
[.github/workflows/dependabot.yml]
- Add a Dependabot workflow for Go modules
- Add a Dependabot workflow for GitHub Actions
Signed-off-by: Neil Naveen <42328488+neilnaveen@users.noreply.github.com>

Set up Dependabot for Go modules and GitHub Actions

---

spdx/model.go
spdxlib/documents_test.go

- Update the `CatagorySecurity` to `CategorySecurity` in `model.go`
- Add `file1` to the list of files in `documents_test.go` to increase coverage
- Add a validation test for an invalid document with an invalid relationship in `documents_test.go`
[spdx/model.go]
- Change `CatagorySecurity` to `CategorySecurity` [spdxlib/documents_test.go]
- Add `file1` to the list of files
- Change the relationship between `p1` and `p99` to `DEPENDS_ON`
- Add a validation test for an invalid document with an invalid relationship

Improve SPDX document validation

---

spdx/v2/v2_2/document.go
spdx/v2/v2_2/json/json_test.go
spdx/v2/v2_2/package.go
spdx/v2/v2_2/yaml/yaml_test.go
spdx/v2/v2_3/document.go
spdx/v2/v2_3/json/json_test.go
spdx/v2/v2_3/package.go
spdx/v2/v2_3/tagvalue/tagvalue_test.go
spdx/v2/v2_3/yaml/yaml_test.go

The JSON schema has fields [documentDescribes](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L219) and [hasFiles](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/schemas/spdx-schema.json#L345) for packages. These are not part of the Go data model and are duplicates of using relationships. However, some tools are outputting these fields today and we need to be able to decode them. This PR adds support for decoding these fields and translating them into the appropriate relationships.
Fixes: #166 
Fixes: #171

fix: read shortcut fields: documentDescribes and hasFiles

---

spdx/v2/v2_2/example/example.go
spdx/v2/v2_2/json/json_test.go
spdx/v2/v2_2/package.go
spdx/v2/v2_3/document.go
spdx/v2/v2_3/json/json_test.go
spdx/v2/v2_3/package.go

Addressing #196 
Sets PACKAGE_MANAGER for v2_2 external reference and PACKAGE-MANAGER  for v2_3.

JSON reading sets appropriate PACKAGE-MANAGER enum based on ver

---

spdx/v2/v2_1/creation_info.go
spdx/v2/v2_1/package.go
spdx/v2/v2_2/creation_info.go
spdx/v2/v2_2/package.go
spdx/v2/v2_3/creation_info.go
spdx/v2/v2_3/package.go

- Package copyrightText field (optional starting in 2.3 - PR includes change)
- 2.3: https://spdx.github.io/spdx-spec/v2.3/package-information/#717-copyright-text-field
- LicenseListFIeld field (optional  - PR includes change)
- 2.3: https://spdx.github.io/spdx-spec/v2.3/document-creation-information/#67-license-list-version-field
- 2.2: https://spdx.github.io/spdx-spec/v2.2.2/document-creation-information/#67-license-list-version-field
- 2.1: Clause 2.7 in https://spdx.dev/spdx-specification-21-web-version/
- packageVerificationCode, looks like this is the same for 2.2 and 2.1 as it is for 2.3, 2.1 and 2.2 need to be updated (PR includes change)

Fixing some optional params: copyrightText, licenseListVersion, packageVerificationCode

---

spdx/v2/v2_2/document.go
spdx/v2/v2_2/example/example.go
spdx/v2/v2_2/json/json_test.go
spdx/v2/v2_2/yaml/yaml_test.go
spdx/v2/v2_3/document.go
spdx/v2/v2_3/json/json_test.go
spdx/v2/v2_3/yaml/yaml_test.go

In the unmarshaling of shorthand fields, checks if relationships exists before adding them.
Fixes #208

Ensure no duplicates in relationships when shortcut fields are used.

---

spdx/v2/v2_2/document.go
spdx/v2/v2_2/json/json_test.go
spdx/v2/v2_3/document.go
spdx/v2/v2_3/json/json_test.go

Really fix #208 :). We forgot to check for the opposite relationships (e.g. CONTAINS_BY and CONTAINED_BY are both considered the same and a new CONTAINS relationship shouldn't be added by shorthand field)

fix duplicate shorthand relationships for opposite case

---

json/reader_test.go
json/test_fixtures/spdx2_3.json
spdx/v2/common/package.go
spdx/v2/common/package_test.go

Given the field `"originator" : "Organization:SPDX",` `tools-golang` would error on decoding a valid SBOM.
This change adds test protection to the reader for any future changes to 2_3 custom unmarshalling as well as fixes the underlying error where the originator field will consider both `: ` and `:` as valid split cases.

Fix: SPDX decode error originator

---

Makefile
convert/spdx_document_conversion_test.go
json/marshal/json.go
json/marshal/json_test.go
json/writer_test.go
spdx/v2/common/annotation.go
spdx/v2/common/creation_info.go
spdx/v2/common/identifier.go
spdx/v2/common/identifier_test.go
spdx/v2/common/package.go
spdx/v2/v2_2/package.go
spdx/v2/v2_3/package.go
spdxlib/described_elements.go

This PR modifies the JSON output behavior to prevent HTML escaping within custom `MarshalJSON` calls. By calling `json.Marshal`, the behavior is to use the default of _escaping HTML_ characters. This PR introduces a `marshal.JSON` function that can be used as a drop-in replacement for `json.Marshal` with HTML escaping disabled.
This prevents things like `Author: Keith <keith@example.com>` from getting escaped unnecessarily to something like: `Author: Keith &lt;keith@example.com&gt;`
Depends on #223

Stop escaping HTML

---

utils/verification.go

`excludeFile` for `GetVerificationCode` function is optional field.
We can avoid creating an empty array for`ExcludedFiles` if `excludeFile` is empty.
Before:
```json
"packageVerificationCode": {
"packageVerificationCodeValue": "a30b237d03b2e0ae8df0801c0bc0f519d2cac6c0",
"packageVerificationCodeExcludedFiles": [
""
]
},
```
After:
```json
"packageVerificationCode": {
"packageVerificationCodeValue": "a30b237d03b2e0ae8df0801c0bc0f519d2cac6c0"
},
```

refactor(verification): don't create empty `ExcludedFiles` array

---

spdx/model.go
spdx/v2/common/external.go

I was missing the External Reference Category "Other" from [Annex F of the 2.3 spec (F.5)](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/). This adds it.

feat: add external reference category "OTHER"

---

spdx/v2/v2_2/json/empty_values_test.go
spdx/v2/v2_2/package.go

In SPDX 2.2, the `packageVerificationCode` element is optional, but the Go struct does not allow this to be omitted. This was corrected by changing the type to a pointer in SPDX 2.3, but still is an issue in SPDX 2.2. In the case `filesAnalyzed` is `false`, it is _required_ to omit this field. This PR implements a simple method to remove emtpy `packageVerificationCode` entries in SPDX 2.2, specifically.

fix(2.2 json): remove emtpy packageVerificationCode

---

.gitattributes
.github/workflows/build.yml
builder/build_package.go
spdx/v2/v2_1/document.go
spdx/v2/v2_2/json/empty_values_test.go
utils/filesystem.go

Since there is Windows-specific code, the tests should also run on Windows.
Fixes: #117

chore: add windows test runner

---

Makefile

While working on a new machine without some of the existing tools like `gosimports`, and when I looked at bumping the go version, there was a friction running `make format`, this just updates the Makefile to be slightly more convenient.

chore: update makefile to include bootstrap and go mod tidy

---

spdx/v2/common/package.go
spdx/v2/common/package_test.go

Provide a clearer error when using an invalid Originator

---

spdx/v2/common/annotation.go
spdx/v2/common/creation_info.go
spdx/v2/common/package.go

issue:
If there is no space after the colon after the json tag prefix, a parsing error occurs. 
fix.

Change the colon and space separator to just a colon
