v0/tvsaver/saver2v1/save_file.go
v0/tvsaver/saver2v1/save_file_test.go

Fixes #8
Signed-off-by: Steve Winslow <swinslow@gmail.com>

Fix wrapping of multiline FileCopyrightText

---

v0/tvloader/parser2v1/parse_package.go
v0/tvloader/parser2v1/parse_package_test.go

Fix tvloader package loading after unpackaged files

---

.github/workflows/build.yml
README.md

Fix badge for GitHub Actions

---

README.md

Fix link for actions badge

---

spdx/creation_info.go
tvloader/parser2v1/parse_creation_info.go
tvloader/parser2v1/parse_creation_info_test.go
tvloader/parser2v2/parse_creation_info.go
tvloader/parser2v2/parse_creation_info_test.go
tvsaver/saver2v1/save_creation_info.go
tvsaver/saver2v1/save_creation_info_test.go
tvsaver/saver2v2/save_creation_info.go
tvsaver/saver2v2/save_creation_info_test.go

Change ExternalDocumentReferences to structured data

---

spdx/creation_info.go
tvloader/parser2v1/parse_creation_info.go
tvloader/parser2v1/parse_creation_info_test.go
tvloader/parser2v1/parser_test.go
tvloader/parser2v2/parse_creation_info.go
tvloader/parser2v2/parse_creation_info_test.go
tvloader/parser2v2/parser_test.go

Fix tvloader storing incorrect doc ID

---

README.md
go.sum

Update README and go.sum for rdfloader

---

examples/7-rdfloader/exampleRDFLoader.go
rdfloader/parser2v2/constants.go
rdfloader/parser2v2/license_utils.go
rdfloader/parser2v2/license_utils_test.go
rdfloader/parser2v2/parse_annotation_test.go
rdfloader/parser2v2/parse_creation_info_test.go
rdfloader/parser2v2/parse_file_test.go
rdfloader/parser2v2/parse_license_test.go
rdfloader/parser2v2/parse_other_license_info_test.go
rdfloader/parser2v2/parse_package_test.go
rdfloader/parser2v2/parse_relationship_test.go
rdfloader/parser2v2/parse_review_test.go
rdfloader/parser2v2/parse_snippet_info_test.go
rdfloader/parser2v2/parse_spdx_document_test.go
rdfloader/parser2v2/parser_test.go
rdfloader/parser2v2/types.go
rdfloader/parser2v2/utils.go
rdfloader/parser2v2/utils_test.go
rdfloader/rdfloader.go
rdfloader/rdfloader_test.go

Add missing license ids

---

README.md

Update README for v0.1.0 release

---

builder/build_test.go
builder/builder2v2/build_file.go
builder/builder2v2/build_file_test.go
builder/builder2v2/build_package_test.go
licensediff/licensediff_test.go
rdfloader/parser2v2/parse_file.go
rdfloader/parser2v2/parse_file_test.go
rdfloader/parser2v2/parse_package.go
rdfloader/parser2v2/parse_package_test.go
rdfloader/parser2v2/parser_test.go
spdx/checksum.go
spdx/file.go
spdx/package.go
tvloader/parser2v2/parse_file.go
tvloader/parser2v2/parse_file_test.go
tvloader/parser2v2/parse_package.go
tvloader/parser2v2/parse_package_test.go
tvsaver/saver2v2/save_document_test.go
tvsaver/saver2v2/save_file.go
tvsaver/saver2v2/save_file_test.go
tvsaver/saver2v2/save_package.go
tvsaver/saver2v2/save_package_test.go
utils/verification.go
utils/verification_test.go

[Optional Upgrade] Checksum Struct done .

---

jsonloader2v2/jsonfiles/test.json
jsonloader2v2/jsonloader.go
jsonloader2v2/jsonloader_test.go
jsonloader2v2/parse_annotations.go
jsonloader2v2/parse_annotations_test.go
jsonloader2v2/parse_creation_info.go
jsonloader2v2/parse_creation_info_test.go
jsonloader2v2/parse_reationship.go
jsonloader2v2/parse_reationship_test.go
jsonloader2v2/types.go
jsonloader2v2/util.go
jsonloader2v2/util_test.go

GSoC'2021 Pull Request 1 :
Weekly Deliverables :

[GSoC'21] Pr:1 . Setup JSON Parser

---

CONTRIBUTING.md

Fix statement about docs license

---

jsonloader/parser2v2/parse_package.go
jsonloader/parser2v2/parse_reviews.go
jsonloader/parser2v2/parse_reviews_test.go
jsonloader/parser2v2/parse_snippets.go
jsonloader/parser2v2/parser.go
jsonloader/parser2v2/parser_test.go

GSoC'2021 Pull Request 4 :
Deliverables Completed :

[GSoC'21] Pr:4 . Complete the JSON parser

---

tvloader/parser2v1/parse_creation_info.go
tvloader/parser2v1/parse_file.go
tvloader/parser2v1/parse_file_test.go
tvloader/parser2v1/parse_package.go
tvloader/parser2v1/parse_package_test.go
tvloader/parser2v1/parse_snippet.go
tvloader/parser2v1/parse_snippet_test.go
tvloader/parser2v1/parser.go
tvloader/parser2v1/parser_test.go
tvloader/parser2v1/types.go
tvloader/parser2v2/parse_creation_info.go
tvloader/parser2v2/parse_file.go
tvloader/parser2v2/parse_file_test.go
tvloader/parser2v2/parse_package.go
tvloader/parser2v2/parse_package_test.go
tvloader/parser2v2/parse_snippet.go
tvloader/parser2v2/parse_snippet_test.go
tvloader/parser2v2/parser.go
tvloader/parser2v2/parser_test.go
tvloader/parser2v2/types.go

Throw error for pkgs / files without SPDX IDs

---

tvsaver/saver2v1/save_package.go
tvsaver/saver2v1/save_package_test.go
tvsaver/saver2v2/save_package.go
tvsaver/saver2v2/save_package_test.go

Fix missing colon for excludes in PackageVerificationCode

---

tvsaver/saver2v1/save_file.go
tvsaver/saver2v1/save_file_test.go
tvsaver/saver2v1/save_package.go
tvsaver/saver2v1/save_package_test.go
tvsaver/saver2v1/save_relationship.go
tvsaver/saver2v1/save_relationship_test.go
tvsaver/saver2v1/save_review.go
tvsaver/saver2v1/save_review_test.go
tvsaver/saver2v2/save_file.go
tvsaver/saver2v2/save_file_test.go
tvsaver/saver2v2/save_package.go
tvsaver/saver2v2/save_package_test.go
tvsaver/saver2v2/save_relationship.go
tvsaver/saver2v2/save_relationship_test.go
tvsaver/saver2v2/save_review.go
tvsaver/saver2v2/save_review_test.go

Fix multi-line text wrapping fields

---

README.md
RELEASE-NOTES.md
examples/README.md
spdxlib/documents.go
spdxlib/element_ids.go
spdxlib/element_ids_test.go
spdxlib/relationships.go
spdxlib/relationships_test.go

Update documentation for 0.2.0 release

---

README.md

Fix link to release notes

---

docs/jsonloader.md
docs/jsonsaver.md

Minor fixes for json documentation

---

README.md

Add OpenSSF best practices badge in progress

---

README.md

Update readme for 0.3.0-rc1

---

README.md
RELEASE-NOTES.md

release: Update docs for 0.3.0 release

---

.github/workflows/build.yml

Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Update build workflow to go 1.18

---

MAINTAINERS
README.md
SECURITY.md

Adding security.md and list of maintainers to contact. 
@swinslow @RishabhBhatnagar can you help verify your information in the file: MAINTAINERS.
Signed-off-by: Brandon Lum <lumjjb@gmail.com>

Add security.md

---

.github/workflows/build.yml
.gitignore
Makefile
utils/filesystem_test.go
utils/verification_test.go

- Including fuzzing for files for utils
Signed-off-by: Neil Naveen <42328488+neilnaveen@users.noreply.github.com>

Included fuzzing for utils

---

README.md

Add support of SPDX 2.3
